### PR TITLE
[86bzgwjyz][notice] changed close icon to button component

### PR DESCRIPTION
**Pull request by ilyabrower**
## Motivation and Context
Just changed close icon to Button component in Notice.

## How has this been tested?
Manually

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [X] Nice improve.

## Checklist:

- [X] My code follows the code style of this project.
- [X] I have updated the documentation accordingly or it's not required.
- [X] Unit tests are not broken.
- [X] I have added changelog note to corresponding `CHANGELOG.md` file with planned publish date.
- [ ] I have added new unit tests on added of fixed functionality.

### CODE REVIEW

**Review by sheila-semrush — COMMENTED** [review]
Everything's good!
Let's decide whether we want to add the title & text properties (or child components).
If no, I'll add the margins in the examples and the playground (will make a commit to the same PR).

**Comment by ilyabrower** [comment]
> Everything's good! Let's decide whether we want to add the title & text properties (or child components). If no, I'll add the margins in the examples and the playground (will make a commit to the same PR).

Not now, maybe sometimes)

**Comment by sheila-semrush** [comment]
@j-mnizhek can you look at the docs? I've updated illustrations and examles, added margins to the text in all examples and the playground to align it with the icon. I've also edited the FeedbackYesNo example to center everything.

@ilyabrower can you take a quick look at the `feedbackyesno-example.tsx`? I've changed some attributes to center all elements, want to make sure that my changes are ok.

**Review by sheila-semrush — APPROVED** [review]

**Review by j-mnizhek — APPROVED** [review]
Updated illustrations for:
- FeedbackRating
- FeedbackYesNo

Also we've discussed today to senter Close button for FeedbackRating.

Everything other looks good!

**Comment by ilyabrower** [comment]
> Updated illustrations for:
> 
> * FeedbackRating
> * FeedbackYesNo
> 
> Also we've discussed today to senter Close button for FeedbackRating.
> 
> Everything other looks good!

I've centered close button

**Review by msereniti — APPROVED** [review]

**Pull request merged**
