### PR TITLE
Fix/old docs cleanup

### PR DESCRIPTION
**Pull request by ilyabrower**
I've just removed dead code.

### CODE REVIEW

**Comment by ilyabrower** [comment]
@Valeria-Zimnitskaya could you make some smoke for the documentation?

**Review by Valeria-Zimnitskaya — CHANGES_REQUESTED** [review]
нашла пару багов - похоже лишнее удалилось
описание тут
https://app.clickup.com/t/86c0kz1z9

**Comment by j-mnizhek** [comment]
Hey hey!
Maybe we can also remove unused variables that were made specifically for the old website?
https://github.com/semrush/intergalactic/blob/master/semcore/utils/theme/exclude-tokens.json

They don't used elsewhere.

**Comment by ilyabrower** [comment]
> Hey hey! Maybe we can also remove unused variables that were made specifically for the old website? https://github.com/semrush/intergalactic/blob/master/semcore/utils/theme/exclude-tokens.json
> 
> They don't used elsewhere.

Let's put it into another task. It doesn't relate to current MR

**Review by Valeria-Zimnitskaya — APPROVED** [review]

**Pull request merged**
